# Configuração do ngrok para o projeto SyncPay
version: "2"
authtoken: null  # Configure seu token aqui se necessário

tunnels:
  syncpay:
    addr: 3000
    proto: http
    inspect: true
    bind_tls: true
    hostname: null  # Deixe null para URL aleatória
